import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { WalletProvider } from '../src/context/WalletProvider'
import Header from '../src/components/Header'
import Transfer from '../src/components/Transfer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <WalletProvider>
      <Head>
        <title>Payment dApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header />
        <main className='flex justify-center'>
          <Transfer />
        </main>
      </>
    </WalletProvider>
  )
}
